/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BuddyBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/api.ts
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));

// src/types.ts
var CURRENT_SETTINGS_VERSION = 7;
var DATA_VERSION = 1;
var DEFAULT_SETTINGS = {
  codebuddyPath: "",
  maxConversations: 20,
  primaryColor: "",
  timeoutSeconds: 300,
  nodePath: "",
  noteLinkInjection: true,
  vaultContextInjection: false,
  version: CURRENT_SETTINGS_VERSION
};
function isObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function getString(data, key) {
  const value = data[key];
  return typeof value === "string" ? value : void 0;
}
function getNumber(data, key) {
  const value = data[key];
  return typeof value === "number" ? value : void 0;
}
function getErrorMessage(error) {
  if (error instanceof Error) {
    return error.message;
  }
  if (typeof error === "string") {
    return error;
  }
  return "\u672A\u77E5\u9519\u8BEF";
}
function migrateSettings(stored) {
  var _a;
  if (!isObject(stored)) {
    return { ...DEFAULT_SETTINGS };
  }
  const maxConversations = getNumber(stored, "maxConversations");
  const primaryColor = getString(stored, "primaryColor");
  const timeoutSeconds = getNumber(stored, "timeoutSeconds");
  const nodePath = getString(stored, "nodePath");
  const noteLinkInjection = typeof stored.noteLinkInjection === "boolean" ? stored.noteLinkInjection : DEFAULT_SETTINGS.noteLinkInjection;
  const vaultContextInjection = typeof stored.vaultContextInjection === "boolean" ? stored.vaultContextInjection : DEFAULT_SETTINGS.vaultContextInjection;
  return {
    codebuddyPath: (_a = getString(stored, "codebuddyPath")) != null ? _a : DEFAULT_SETTINGS.codebuddyPath,
    maxConversations: typeof maxConversations === "number" && maxConversations > 0 ? maxConversations : DEFAULT_SETTINGS.maxConversations,
    primaryColor: primaryColor != null ? primaryColor : DEFAULT_SETTINGS.primaryColor,
    timeoutSeconds: typeof timeoutSeconds === "number" && timeoutSeconds > 0 ? timeoutSeconds : DEFAULT_SETTINGS.timeoutSeconds,
    nodePath: nodePath != null ? nodePath : DEFAULT_SETTINGS.nodePath,
    noteLinkInjection,
    vaultContextInjection,
    version: CURRENT_SETTINGS_VERSION
  };
}
function generateId() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === "x" ? r : r & 3 | 8;
    return v.toString(16);
  });
}
function normalizeConversation(raw) {
  var _a, _b, _c, _d, _e;
  if (!isObject(raw))
    return null;
  const id = (_a = getString(raw, "id")) != null ? _a : generateId();
  const title = (_b = getString(raw, "title")) != null ? _b : "\u65B0\u5BF9\u8BDD";
  const sessionId = (_c = getString(raw, "sessionId")) != null ? _c : "";
  const messages = Array.isArray(raw.messages) ? raw.messages : [];
  const createdAt = (_d = getNumber(raw, "createdAt")) != null ? _d : Date.now();
  const updatedAt = (_e = getNumber(raw, "updatedAt")) != null ? _e : createdAt;
  return { id, title, sessionId, messages, createdAt, updatedAt };
}
function normalizePersistedData(raw) {
  const result = { dataVersion: DATA_VERSION };
  if (!isObject(raw)) {
    return result;
  }
  const dataVersion = getNumber(raw, "dataVersion");
  if (typeof dataVersion === "number") {
    result.dataVersion = dataVersion;
  }
  if (Array.isArray(raw.conversations)) {
    const convs = [];
    for (const item of raw.conversations) {
      const conv = normalizeConversation(item);
      if (conv)
        convs.push(conv);
    }
    result.conversations = convs;
  }
  if (isObject(raw.settings)) {
    result.settings = migrateSettings(raw.settings);
  }
  return result;
}

// src/api.ts
var TIMEOUT = 3e5;
var NODE_EXECUTABLE = process.platform === "win32" ? "node.exe" : "node";
function findNodeExecutable() {
  const home = process.env.HOME || process.env.USERPROFILE || "";
  const nodeDirs = [];
  if (process.platform === "win32") {
    nodeDirs.push(path.dirname(process.execPath));
    const appData = process.env.APPDATA || "";
    if (appData) {
      nodeDirs.push(appData);
      nodeDirs.push(path.join(appData, "npm"));
    }
    const programFiles = process.env.ProgramFiles || "C:\\Program Files";
    const programFilesX86 = process.env["ProgramFiles(x86)"] || "C:\\Program Files (x86)";
    const localAppData = process.env.LOCALAPPDATA || "";
    nodeDirs.push(
      path.join(programFiles, "nodejs"),
      path.join(programFilesX86, "nodejs")
    );
    if (localAppData) {
      nodeDirs.push(path.join(localAppData, "Programs", "nodejs"));
    }
    const nvmSymlink = process.env.NVM_SYMLINK;
    if (nvmSymlink) {
      nodeDirs.push(nvmSymlink);
    }
    if (home) {
      const wbNodeVersionsDir = path.join(home, ".workbuddy", "binaries", "node", "versions");
      try {
        const versions = fs.readdirSync(wbNodeVersionsDir);
        for (const v of versions) {
          nodeDirs.push(path.join(wbNodeVersionsDir, v));
        }
      } catch (e) {
      }
    }
    for (const drive of ["C:", "D:", "E:"]) {
      if (drive + "\\" !== path.parse(programFiles).root.toUpperCase()) {
        nodeDirs.push(path.join(drive + "\\Program Files", "nodejs"));
      }
    }
  } else {
    nodeDirs.push(
      path.join(home, ".local", "bin"),
      path.join(home, ".npm-global", "bin"),
      path.join(home, ".volta", "bin"),
      path.join(home, "bin", "codebuddy"),
      "/usr/local/bin/codebuddy",
      "/opt/homebrew/bin/codebuddy"
    );
    const nvmBin = process.env.NVM_BIN;
    if (nvmBin) {
      nodeDirs.push(nvmBin);
    }
  }
  for (const dir of nodeDirs) {
    if (!dir)
      continue;
    try {
      const nodePath = path.join(dir, NODE_EXECUTABLE);
      if (fs.existsSync(nodePath) && fs.statSync(nodePath).isFile()) {
        console.log("[BB] found node at:", nodePath);
        return nodePath;
      }
    } catch (e) {
    }
  }
  console.log("[BB] WARNING: node not found in any search path, falling back to 'node'");
  return "node";
}
function resolveCodebuddyPath(customPath) {
  if (customPath) {
    return customPath;
  }
  if (process.env.CODEBUDDY_PATH && fs.existsSync(process.env.CODEBUDDY_PATH)) {
    return process.env.CODEBUDDY_PATH;
  }
  const home = process.env.HOME || process.env.USERPROFILE || "";
  const localAppData = process.env.LOCALAPPDATA || "";
  const appData = process.env.APPDATA || "";
  const programFiles = process.env.ProgramFiles || "C:\\Program Files";
  const programFilesX86 = process.env["ProgramFiles(x86)"] || "C:\\Program Files (x86)";
  const candidates = [];
  if (process.platform === "win32") {
    candidates.push(
      path.join(localAppData, "Programs", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.exe"),
      path.join(localAppData, "Programs", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.cmd"),
      path.join(localAppData, "Programs", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy")
    );
    if (appData) {
      candidates.push(path.join(appData, "npm", "codebuddy.cmd"));
      candidates.push(path.join(appData, "npm", "codebuddy"));
    }
    candidates.push(
      path.join(programFiles, "nodejs", "codebuddy.cmd"),
      path.join(programFiles, "nodejs", "node_modules", ".bin", "codebuddy.cmd"),
      path.join(programFilesX86, "nodejs", "node_modules", ".bin", "codebuddy.cmd"),
      path.join(programFiles, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.exe"),
      path.join(programFiles, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.cmd"),
      path.join(programFiles, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy"),
      path.join(programFilesX86, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.exe"),
      path.join(programFilesX86, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.cmd"),
      path.join(programFilesX86, "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy")
    );
    for (const drive of ["C:", "D:", "E:"]) {
      candidates.push(
        path.join(drive + "\\Program Files", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.exe"),
        path.join(drive + "\\Program Files", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy.cmd"),
        path.join(drive + "\\Program Files", "WorkBuddy", "resources", "app.asar.unpacked", "cli", "bin", "codebuddy")
      );
    }
  } else {
    candidates.push(
      path.join(home, ".local", "bin", "codebuddy"),
      path.join(home, ".npm-global", "bin", "codebuddy"),
      path.join(home, ".volta", "bin", "codebuddy"),
      path.join(home, "bin", "codebuddy"),
      "/usr/local/bin/codebuddy",
      "/opt/homebrew/bin/codebuddy"
    );
  }
  const nvmBin = process.env.NVM_BIN;
  if (nvmBin)
    candidates.push(path.join(nvmBin, "codebuddy"));
  const npmPrefix = process.env.npm_config_prefix;
  if (npmPrefix)
    candidates.push(path.join(npmPrefix, "bin", "codebuddy"));
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      console.log("[BB] resolved codebuddy path:", p);
      return p;
    }
  }
  const envPath = process.env.PATH || "";
  const pathSep = process.platform === "win32" ? ";" : ":";
  const exeNames = process.platform === "win32" ? ["codebuddy.exe", "codebuddy.cmd", "codebuddy"] : ["codebuddy"];
  for (const dir of envPath.split(pathSep)) {
    if (!dir)
      continue;
    for (const name of exeNames) {
      try {
        const p = path.join(dir, name);
        if (fs.existsSync(p))
          return p;
      } catch (e) {
      }
    }
  }
  return "codebuddy";
}
function parseMessageBlock(block) {
  if (!isObject(block))
    return null;
  const type = getString(block, "type");
  if (type !== "thinking" && type !== "text" && type !== "tool_call")
    return null;
  return {
    type,
    thinking: getString(block, "thinking"),
    text: getString(block, "text"),
    name: getString(block, "name"),
    input: block.input
  };
}
function blockToChunk(block) {
  if (block.type === "thinking") {
    return { type: "thinking", content: block.thinking || "" };
  }
  if (block.type === "text") {
    return { type: "text", content: block.text || "" };
  }
  const input = block.input;
  return {
    type: "tool",
    content: "",
    toolName: block.name || "unknown",
    toolDetail: typeof input === "string" ? input : JSON.stringify(input != null ? input : {})
  };
}
function parseStreamEvent(raw) {
  if (!isObject(raw))
    return null;
  const event = isObject(raw.event) ? raw.event : raw;
  if (!isObject(event))
    return null;
  return {
    type: getString(event, "type") || "",
    thinking: getString(event, "thinking"),
    text: getString(event, "text"),
    name: getString(event, "name"),
    input: event.input,
    result: getString(event, "result"),
    error: getString(event, "error"),
    message: getString(event, "message"),
    content: getString(event, "content")
  };
}
function parseStreamLine(line) {
  if (!line.trim())
    return null;
  try {
    const raw = JSON.parse(line);
    if (isObject(raw) && (raw.type === "assistant" || raw.type === "user")) {
      const message = isObject(raw.message) ? raw.message : null;
      const content = Array.isArray(message == null ? void 0 : message.content) ? message.content : [];
      for (const item of content) {
        const block = parseMessageBlock(item);
        if (block) {
          const chunk = blockToChunk(block);
          if (chunk)
            return chunk;
        }
      }
      return null;
    }
    const event = parseStreamEvent(raw);
    if (!event)
      return null;
    if (event.type === "thinking") {
      return { type: "thinking", content: event.thinking || "" };
    }
    if (event.type === "message_delta") {
      return { type: "text", content: event.text || "" };
    }
    if (event.type === "tool_call") {
      const input = event.input;
      return {
        type: "tool",
        content: "",
        toolName: event.name || "unknown",
        toolDetail: typeof input === "string" ? input : JSON.stringify(input != null ? input : {})
      };
    }
    if (event.type === "result") {
      return { type: "done", content: event.result || "" };
    }
    if (event.type === "error") {
      return { type: "error", content: event.error || event.message || "\u672A\u77E5\u9519\u8BEF" };
    }
    console.log("[BB] unknown event:", line.substring(0, 200));
    const fallbackText = event.text || event.content || event.message || "";
    if (fallbackText) {
      return { type: "text", content: fallbackText };
    }
    return null;
  } catch (e) {
    return { type: "text", content: line };
  }
}
function isWindowsWrapper(scriptPath) {
  return scriptPath.endsWith(".cmd") || scriptPath.endsWith(".exe") || scriptPath.endsWith(".bat");
}
function isStartupBanner(text) {
  return /^(Working directory|file operation|file rules|Standing by|Awaiting|Confirmed|Vault path|待命中|文件操作|已锁定|已确认|工作目录)/i.test(text.trim());
}
function isBareFallback(scriptPath) {
  return scriptPath === "codebuddy" || !path.isAbsolute(scriptPath);
}
function needsWindowsShell(scriptPath) {
  return process.platform === "win32" && (scriptPath.endsWith(".cmd") || scriptPath.endsWith(".bat"));
}
function escapeCmdArg(text) {
  if (text === "")
    return '""';
  const escaped = text.replace(/([&|><^"()%!])/g, "^$1");
  return `"${escaped}"`;
}
var BuddyBridgeAPI = class {
  constructor(timeout = TIMEOUT) {
    this.nodePath = "";
    this.currentProc = null;
    this.timeout = timeout;
    this.scriptPath = resolveCodebuddyPath("");
  }
  setCodebuddyPath(p) {
    this.scriptPath = resolveCodebuddyPath(p);
  }
  /** 手动指定 Node.js 路径（设置项 nodePath）；留空则自动检测。 */
  setNodePath(p) {
    this.nodePath = p || "";
  }
  getNodePath() {
    return this.nodePath;
  }
  /** 设置请求超时时长（毫秒）。由设置页 timeoutSeconds 驱动（默认 300s）。 */
  setTimeoutMs(ms) {
    if (typeof ms === "number" && ms > 0) {
      this.timeout = ms;
    }
  }
  getTimeoutMs() {
    return this.timeout;
  }
  generateId() {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = Math.random() * 16 | 0;
      const v = c === "x" ? r : r & 3 | 8;
      return v.toString(16);
    });
  }
  async *sendMessage(sessionId, text, vaultPath) {
    var _a, _b;
    const scriptPath = this.scriptPath;
    const procOptions = {
      // 不再使用 spawn 的 timeout（P0.3）：改为插件侧计时，超时产出明确错误卡
      stdio: ["ignore", "pipe", "pipe"]
    };
    if (vaultPath) {
      procOptions.cwd = vaultPath;
    }
    let cliArgs = ["--print", "--output-format", "stream-json", "--session-id", sessionId, text];
    if (needsWindowsShell(scriptPath)) {
      procOptions.shell = true;
      cliArgs = [...cliArgs.slice(0, -1), escapeCmdArg(text)];
    }
    let proc;
    if (isWindowsWrapper(scriptPath) || isBareFallback(scriptPath)) {
      proc = (0, import_child_process.spawn)(scriptPath, cliArgs, procOptions);
    } else {
      const nodeBin = this.nodePath || findNodeExecutable() || "node";
      proc = (0, import_child_process.spawn)(nodeBin, [scriptPath, ...cliArgs], procOptions);
    }
    this.currentProc = proc;
    let timedOut = false;
    const timeoutSeconds = Math.max(1, Math.round(this.timeout / 1e3));
    const timer = setTimeout(() => {
      if (closed)
        return;
      timedOut = true;
      try {
        proc.kill();
      } catch (e) {
      }
      const errChunk = {
        type: "error",
        content: `\u8BF7\u6C42\u8D85\u65F6\uFF08\u5DF2\u7B49\u5F85 ${timeoutSeconds} \u79D2\uFF09\uFF0C\u8BF7\u68C0\u67E5 CodeBuddy CLI \u662F\u5426\u6B63\u5E38\u8FD0\u884C\u6216\u5C1D\u8BD5\u91CD\u8BD5`
      };
      if (resolveQueue) {
        resolveQueue({ value: errChunk, done: false });
        resolveQueue = null;
      } else {
        chunkQueue.push(errChunk);
      }
    }, this.timeout);
    (_a = timer.unref) == null ? void 0 : _a.call(timer);
    let buffer = "";
    let errOut = "";
    let hasOutput = false;
    const chunkQueue = [];
    let resolveQueue = null;
    let closed = false;
    proc.stdout.on("data", (d) => {
      buffer += d.toString();
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        const chunk = parseStreamLine(line);
        if (chunk) {
          hasOutput = true;
          const preview = typeof chunk.content === "string" ? chunk.content.substring(0, 80) : JSON.stringify(chunk.content).substring(0, 80);
          console.log("[BB] chunk:", chunk.type, preview);
          if (resolveQueue) {
            resolveQueue({ value: chunk, done: false });
            resolveQueue = null;
          } else {
            chunkQueue.push(chunk);
          }
        }
      }
    });
    proc.stderr.on("data", (d) => {
      errOut += d.toString();
      console.log("[BB] stderr:", errOut);
    });
    proc.on("close", (code, signal) => {
      console.log("[BB] exit:", code, signal ? "signal:" + signal : "", "| err:", errOut.substring(0, 200));
      this.currentProc = null;
      clearTimeout(timer);
      closed = true;
      if (resolveQueue) {
        let result;
        if (hasOutput) {
          result = { value: { type: "done", content: "" }, done: true };
        } else if (code !== 0) {
          const detail = errOut.trim() || `\u8FDB\u7A0B\u5F02\u5E38\u9000\u51FA\uFF08\u9000\u51FA\u7801 ${code}${signal ? `, \u4FE1\u53F7 ${signal}` : ""}\uFF09\uFF0C\u8BF7\u68C0\u67E5 CodeBuddy CLI \u662F\u5426\u6B63\u5E38\u8FD0\u884C`;
          result = { value: { type: "error", content: detail }, done: true };
        } else {
          result = { value: { type: "done", content: "" }, done: true };
        }
        resolveQueue(result);
        resolveQueue = null;
      }
    });
    proc.on("error", (e) => {
      console.log("[BB] spawn err:", e.message, "| scriptPath:", scriptPath);
      clearTimeout(timer);
      closed = true;
      if (resolveQueue) {
        let hint = e.message;
        if (e.message.includes("ENOENT")) {
          if (scriptPath === "codebuddy") {
            hint = "\u627E\u4E0D\u5230 codebuddy CLI\u3002\u8BF7\u786E\u8BA4\u5DF2\u5B89\u88C5 WorkBuddy \u684C\u9762\u7248\uFF0C\u6216\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u6307\u5B9A codebuddy \u8DEF\u5F84\u3002";
          } else if (!isWindowsWrapper(scriptPath) && !isBareFallback(scriptPath)) {
            hint = `\u627E\u4E0D\u5230 Node.js \u6765\u8FD0\u884C codebuddy (\u8DEF\u5F84: ${scriptPath})\u3002\u8BF7\u786E\u8BA4\u5DF2\u5B89\u88C5 Node.js\u3002`;
          }
        }
        resolveQueue({ value: { type: "error", content: hint }, done: true });
        resolveQueue = null;
      }
    });
    while (true) {
      if (chunkQueue.length > 0) {
        const nextChunk = chunkQueue.shift();
        if (nextChunk) {
          yield nextChunk;
          continue;
        }
      }
      if (timedOut) {
        clearTimeout(timer);
        break;
      }
      if (closed) {
        if (buffer.trim()) {
          const chunk = parseStreamLine(buffer);
          if (chunk)
            yield chunk;
        }
        break;
      }
      const next = await new Promise((r) => {
        resolveQueue = r;
      });
      if (next.done) {
        if (((_b = next.value) == null ? void 0 : _b.type) === "error")
          throw new Error(next.value.content);
        break;
      }
      yield next.value;
    }
    clearTimeout(timer);
  }
  cancel() {
    if (this.currentProc) {
      try {
        this.currentProc.kill();
        console.log("[BB] \u5DF2\u7EC8\u6B62 CLI \u8FDB\u7A0B");
      } catch (e) {
        console.error("[BB] \u7EC8\u6B62\u8FDB\u7A0B\u5931\u8D25:", e);
      }
      this.currentProc = null;
    }
  }
};

// src/views/chat.ts
var import_obsidian = require("obsidian");

// src/chat/manager.ts
var ConversationManager = class {
  constructor() {
    this.conversations = /* @__PURE__ */ new Map();
    this.activeId = null;
    this.maxConversations = 20;
    this.persistCallback = null;
  }
  setPersistCallback(callback) {
    this.persistCallback = callback;
  }
  /** 设置最大对话数；创建新对话后按 updatedAt 裁剪（P0.4）。 */
  setMaxConversations(max) {
    if (typeof max === "number" && max > 0) {
      this.maxConversations = max;
    }
  }
  getMaxConversations() {
    return this.maxConversations;
  }
  async persist() {
    if (this.persistCallback) {
      await this.persistCallback(this.getAll());
    }
  }
  handlePersistError(error) {
    console.error("[BB] persist failed:", getErrorMessage(error));
  }
  /** 显式触发持久化（流式结束后调用） */
  async flush() {
    await this.persist();
  }
  /** 从持久化数据加载对话 */
  load(conversations) {
    if (!conversations || conversations.length === 0) {
      this.createConversation();
      return;
    }
    for (const conv of conversations) {
      this.conversations.set(conv.id, { ...conv });
    }
    this.activeId = conversations[0].id;
  }
  /** 创建新对话 */
  createConversation(title) {
    const id = generateId();
    let updatedAt = Date.now();
    for (const c of this.conversations.values()) {
      if (c.updatedAt >= updatedAt)
        updatedAt = c.updatedAt + 1;
    }
    const conv = {
      id,
      title: title || "\u65B0\u5BF9\u8BDD",
      sessionId: "",
      // 首次发送消息时由 Gateway 分配
      messages: [],
      createdAt: Date.now(),
      updatedAt
    };
    this.conversations.set(id, conv);
    this.activeId = id;
    this.trimConversations();
    this.persist().catch((err) => this.handlePersistError(err));
    return conv;
  }
  /**
   * P0.4：按 updatedAt 降序保留最近 maxConversations 个会话，删除更旧的。
   * 若当前活跃会话被裁掉，回退到保留列表中最新的一条。
   */
  trimConversations() {
    var _a, _b;
    if (this.maxConversations <= 0)
      return;
    const all = this.getAll();
    if (all.length <= this.maxConversations)
      return;
    const keepIds = new Set(all.slice(0, this.maxConversations).map((c) => c.id));
    for (const conv of all.slice(this.maxConversations)) {
      this.conversations.delete(conv.id);
    }
    if (this.activeId && !keepIds.has(this.activeId)) {
      this.activeId = (_b = (_a = all[0]) == null ? void 0 : _a.id) != null ? _b : null;
    }
  }
  /** 删除指定消息（用于错误卡重试时移除失败的 user+assistant 对）。返回实际删除条数。 */
  removeMessages(convId, ids) {
    const conv = this.conversations.get(convId);
    if (!conv || !ids || ids.length === 0)
      return 0;
    const before = conv.messages.length;
    conv.messages = conv.messages.filter((m) => !ids.includes(m.id));
    const removed = before - conv.messages.length;
    if (removed > 0) {
      conv.updatedAt = Date.now();
      this.persist().catch((err) => this.handlePersistError(err));
    }
    return removed;
  }
  /** 删除对话 */
  deleteConversation(id) {
    if (!this.conversations.has(id))
      return false;
    this.conversations.delete(id);
    if (this.activeId === id) {
      const remaining = this.getAll();
      this.activeId = remaining.length > 0 ? remaining[0].id : null;
    }
    this.persist().catch((err) => this.handlePersistError(err));
    return true;
  }
  /** 切换到指定对话 */
  switchTo(id) {
    const conv = this.conversations.get(id);
    if (!conv)
      return null;
    this.activeId = id;
    return conv;
  }
  /** 获取当前活跃对话 */
  getActive() {
    if (!this.activeId)
      return null;
    return this.conversations.get(this.activeId) || null;
  }
  /** 获取所有对话（按更新时间倒序） */
  getAll() {
    return Array.from(this.conversations.values()).sort((a, b) => b.updatedAt - a.updatedAt);
  }
  /** 添加消息到当前活跃对话 */
  addMessage(convId, role, content) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return null;
    const msg = {
      id: generateId(),
      role,
      content,
      timestamp: Date.now()
    };
    conv.messages.push(msg);
    conv.updatedAt = Date.now();
    if (conv.title === "\u65B0\u5BF9\u8BDD" && role === "user" && content.trim()) {
      conv.title = content.substring(0, 30) + (content.length > 30 ? "..." : "");
    }
    this.persist().catch((err) => this.handlePersistError(err));
    return msg;
  }
  /** 更新指定消息内容（用于流式追加） */
  updateMessage(convId, msgId, content, skipSave = false) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return false;
    const msg = conv.messages.find((m) => m.id === msgId);
    if (!msg)
      return false;
    msg.content = content;
    conv.updatedAt = Date.now();
    if (!skipSave) {
      this.persist().catch((err) => this.handlePersistError(err));
    }
    return true;
  }
  /** 更新指定消息的结构化 parts（思考 / 工具调用），供流式结束后重建展示块。 */
  updateMessageParts(convId, msgId, parts, skipSave = false) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return false;
    const msg = conv.messages.find((m) => m.id === msgId);
    if (!msg)
      return false;
    msg.parts = parts ? [...parts] : void 0;
    conv.updatedAt = Date.now();
    if (!skipSave) {
      this.persist().catch((err) => this.handlePersistError(err));
    }
    return true;
  }
  /** 设置对话的 Gateway sessionId */
  setSessionId(convId, sessionId) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return false;
    conv.sessionId = sessionId;
    return true;
  }
};

// src/context.ts
function buildPromptContext(input) {
  const lines = [];
  if (input.noteLinkInjection && input.notePath) {
    lines.push(`[\u5F53\u524D\u7B14\u8BB0: ${input.notePath}]`);
  }
  if (input.vaultContextInjection && input.vaultPath) {
    lines.push(`[Vault: ${input.vaultPath}]`);
  }
  if (lines.length === 0) {
    return input.userText;
  }
  return lines.join("\n") + "\n\n" + input.userText;
}
function buildDedupedPrompt(prev, current, userText, flags) {
  if (prev && prev.notePath === current.notePath && prev.vaultPath === current.vaultPath) {
    return { text: userText, state: current };
  }
  let text = buildPromptContext({
    userText,
    notePath: current.notePath,
    vaultPath: current.vaultPath,
    noteLinkInjection: flags.noteLinkInjection,
    vaultContextInjection: flags.vaultContextInjection
  });
  if (flags.noteLinkInjection && (prev == null ? void 0 : prev.notePath) && !current.notePath) {
    text = `[\u5F53\u524D\u7B14\u8BB0: \u65E0]

${text}`;
  }
  return { text, state: current };
}

// src/views/chat.ts
var VIEW_TYPE_CHAT = "buddybridge-panel";
var COMMANDS = {
  "/clear": "\u6E05\u7A7A\u5BF9\u8BDD\uFF0C\u91CD\u65B0\u5F00\u59CB",
  "/help": "\u663E\u793A CodeBuddy \u5E2E\u52A9\u4FE1\u606F",
  "/status": "\u663E\u793A\u5F53\u524D\u4ED3\u5E93\u548C\u4F1A\u8BDD\u72B6\u6001",
  "/doctor": "\u68C0\u67E5 CodeBuddy \u73AF\u5883\u72B6\u6001",
  "/compact": "\u538B\u7F29\u4E0A\u4E0B\u6587\u4EE5\u8282\u7701\u7A7A\u95F4",
  "/summarize": "\u603B\u7ED3\u5E76\u538B\u7F29\u5BF9\u8BDD\u4E0A\u4E0B\u6587",
  "/context": "\u8BA1\u7B97\u5F53\u524D\u4F1A\u8BDD token \u5206\u5E03",
  "/cost": "\u663E\u793A\u4F1A\u8BDD\u6210\u672C\u548C token \u7528\u91CF",
  "/model": "\u67E5\u770B\u6216\u5207\u6362 AI \u6A21\u578B",
  "/permissions": "\u7BA1\u7406\u5DE5\u5177\u548C\u76EE\u5F55\u8BBF\u95EE\u6743\u9650",
  "/config": "\u67E5\u770B\u6216\u4FEE\u6539\u672C\u5730\u914D\u7F6E",
  "/export": "\u5BFC\u51FA\u5F53\u524D\u5BF9\u8BDD",
  "/resume": "\u6062\u590D\u4E4B\u524D\u7684\u4F1A\u8BDD",
  "/rewind": "\u56DE\u9000\u5230\u4E4B\u524D\u7684\u6D88\u606F\u70B9",
  "/init": "\u521D\u59CB\u5316 CodeBuddy \u4ED3\u5E93",
  "/plan": "\u9884\u89C8\u8BA1\u5212\u6A21\u5F0F\u4E0B\u7684\u8BA1\u5212\u6587\u4EF6",
  "/fork": "\u5728\u5F53\u524D\u5BF9\u8BDD\u4F4D\u7F6E\u521B\u5EFA\u5206\u652F",
  "/memory": "\u7BA1\u7406\u957F\u671F\u8BB0\u5FC6",
  "/mcp": "\u7BA1\u7406 MCP \u8FDE\u63A5",
  "/todos": "\u663E\u793A\u5F85\u529E\u4E8B\u9879\u5217\u8868",
  "/stats": "\u663E\u793A\u4F7F\u7528\u7EDF\u8BA1\u4FE1\u606F",
  "/cr": "\u5BA1\u67E5\u4EE3\u7801\u8D28\u91CF",
  "/fix": "\u81EA\u52A8\u4FEE\u590D\u4EE3\u7801\u95EE\u9898",
  "/tests": "\u751F\u6210\u5355\u5143\u6D4B\u8BD5",
  "/explain": "\u89E3\u91CA\u4EE3\u7801\u5DE5\u4F5C\u539F\u7406",
  "/rules": "\u751F\u6210\u4EE3\u7801\u89C4\u8303\u89C4\u5219"
};
var BuddyBridgeChatView = class extends import_obsidian.ItemView {
  constructor(leaf, api, loadDataCallback) {
    super(leaf);
    this.streamingConversations = /* @__PURE__ */ new Set();
    this.streamingMsgId = null;
    this.stopRequested = false;
    this.fileIndex = null;
    this.fileIndexBuiltAt = 0;
    /** 会话内已注入的上下文签名（去重用，内存态；面板重开时重置为重新注入一次） */
    this.contextStates = /* @__PURE__ */ new Map();
    this.api = api;
    this.loadDataCallback = loadDataCallback;
    this.manager = new ConversationManager();
    this.markdownComponent = new import_obsidian.Component();
    this.markdownComponent.load();
  }
  get vaultPath() {
    const adapter = this.app.vault.adapter;
    return adapter.basePath;
  }
  /** 读取插件设置（用于上下文注入开关等）；加载失败时返回 undefined。 */
  get pluginSettings() {
    var _a, _b, _c;
    try {
      return (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["buddybridge"]) == null ? void 0 : _c.settings;
    } catch (e) {
      return void 0;
    }
  }
  /**
   * 构建发送给 CLI 的上下文文本：会话内去重。
   * 笔记 / Vault 上下文「没变化」就不再重复注入，只在变化时注入，
   * 避免 CLI 历史里堆叠 N 行 `[当前笔记: ...]` 导致 agent 误判。
   */
  buildContextText(convId, text) {
    var _a, _b, _c, _d;
    const settings = this.pluginSettings;
    const noteLink = (settings == null ? void 0 : settings.noteLinkInjection) !== false;
    const vaultCtx = !!(settings == null ? void 0 : settings.vaultContextInjection);
    const current = {
      notePath: noteLink ? (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : null : null,
      vaultPath: vaultCtx ? (_c = this.vaultPath) != null ? _c : null : null
    };
    const prev = (_d = this.contextStates.get(convId)) != null ? _d : null;
    const { text: out, state } = buildDedupedPrompt(prev, current, text, {
      noteLinkInjection: noteLink,
      vaultContextInjection: vaultCtx
    });
    this.contextStates.set(convId, state);
    return out;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "BuddyBridge \u804A\u5929";
  }
  getIcon() {
    return "bot";
  }
  getManager() {
    return this.manager;
  }
  async onOpen() {
    var _a, _b, _c, _d, _e;
    const container = this.contentEl;
    container.empty();
    container.addClass("buddybridge-chat-container");
    try {
      const plugin = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["buddybridge"];
      if (plugin == null ? void 0 : plugin.applyPrimaryColor) {
        plugin.applyPrimaryColor();
      }
    } catch (e) {
      console.error("[BB] \u5E94\u7528\u4E3B\u8272\u8C03\u5931\u8D25:", e);
    }
    this.tabBar = container.createDiv({ cls: "buddybridge-tab-bar" });
    const newBtn = this.tabBar.createEl("button", {
      text: "",
      cls: "buddybridge-new-chat-btn",
      attr: { title: "\u65B0\u5EFA\u5BF9\u8BDD", "aria-label": "\u65B0\u5EFA\u5BF9\u8BDD" }
    });
    (0, import_obsidian.setIcon)(newBtn, "plus");
    newBtn.onclick = () => this.createNewChat();
    this.currentFileBar = container.createDiv({ cls: "buddybridge-current-file" });
    this.updateCurrentFileBar();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.updateCurrentFileBar();
      })
    );
    this.messageContainer = container.createDiv({ cls: "buddybridge-messages" });
    const inputArea = container.createDiv({ cls: "buddybridge-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      cls: "buddybridge-input",
      attr: { placeholder: "\u8F93\u5165\u6D88\u606F... (Shift+Enter \u6362\u884C\uFF0CEnter \u53D1\u9001)", rows: "2" }
    });
    this.inputEl.onkeydown = (e) => this.handleKeydown(e);
    this.inputEl.oninput = () => {
      this.adjustTextareaHeight();
      this.updateCommandDropdown();
    };
    this.sendBtn = inputArea.createEl("button", {
      text: "\u53D1\u9001",
      cls: "buddybridge-send-btn",
      attr: { "aria-label": "\u53D1\u9001" }
    });
    this.sendBtn.onclick = () => {
      const conv = this.manager.getActive();
      if (conv && this.streamingConversations.has(conv.id)) {
        this.stopStreaming();
      } else {
        this.sendMessage();
      }
    };
    try {
      const plugin = (_d = (_c = this.app.plugins) == null ? void 0 : _c.plugins) == null ? void 0 : _d["buddybridge"];
      if ((_e = plugin == null ? void 0 : plugin.settings) == null ? void 0 : _e.maxConversations) {
        this.manager.setMaxConversations(plugin.settings.maxConversations);
      }
    } catch (e) {
      console.error("[BB] \u540C\u6B65\u6700\u5927\u5BF9\u8BDD\u6570\u5931\u8D25:", e);
    }
    try {
      const conversations = await this.loadDataCallback();
      await this.loadConversations(conversations);
    } catch (e) {
      console.error("[BB] \u52A0\u8F7D\u5386\u53F2\u5BF9\u8BDD\u5931\u8D25:", e);
    }
  }
  async onClose() {
    this.markdownComponent.unload();
  }
  async loadConversations(conversations) {
    this.manager.load(conversations);
    this.renderTabs();
    await this.renderMessages();
  }
  async createNewChat() {
    this.manager.createConversation();
    this.renderTabs();
    await this.renderMessages();
    this.setInputEnabled(true);
  }
  async switchToChat(id) {
    this.manager.switchTo(id);
    this.renderTabs();
    await this.renderMessages();
    const isSending = this.streamingConversations.has(id);
    this.setInputEnabled(!isSending);
  }
  async deleteChat(id, e) {
    e.stopPropagation();
    this.manager.deleteConversation(id);
    this.renderTabs();
    await this.renderMessages();
  }
  /** 渲染标签栏 */
  renderTabs() {
    var _a;
    const newBtn = this.tabBar.querySelector(".buddybridge-new-chat-btn");
    const oldTabs = this.tabBar.querySelectorAll(".buddybridge-tab");
    oldTabs.forEach((t) => t.remove());
    const conversations = this.manager.getAll();
    const activeId = (_a = this.manager.getActive()) == null ? void 0 : _a.id;
    for (const conv of conversations) {
      const tab = this.tabBar.createDiv({ cls: "buddybridge-tab" });
      if (conv.id === activeId) {
        tab.addClass("buddybridge-tab-active");
      }
      tab.createSpan({ text: conv.title, cls: "buddybridge-tab-title" });
      const closeBtn = tab.createSpan({
        cls: "buddybridge-tab-close",
        attr: { title: "\u5173\u95ED\u5BF9\u8BDD", "aria-label": "\u5173\u95ED\u5BF9\u8BDD", role: "button", tabindex: "0" }
      });
      (0, import_obsidian.setIcon)(closeBtn, "x");
      closeBtn.onclick = (e) => this.deleteChat(conv.id, e);
      closeBtn.onkeydown = (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          void this.deleteChat(conv.id, e);
        }
      };
      tab.onclick = () => this.switchToChat(conv.id);
      if (newBtn) {
        tab.after(newBtn);
      }
    }
  }
  async renderMessages() {
    this.messageContainer.empty();
    const conv = this.manager.getActive();
    if (!conv) {
      const empty = this.messageContainer.createDiv({ cls: "buddybridge-empty-chat" });
      const icon = empty.createDiv({ cls: "buddybridge-empty-chat-icon" });
      (0, import_obsidian.setIcon)(icon, "message-square");
      empty.createDiv({ cls: "buddybridge-empty-chat-title", text: "\u5F00\u59CB\u65B0\u5BF9\u8BDD" });
      empty.createDiv({ cls: "buddybridge-empty-chat-subtitle", text: "\u8F93\u5165\u6D88\u606F\u5F00\u59CB\u804A\u5929\uFF0C\u6216\u70B9\u51FB + \u65B0\u5EFA\u5BF9\u8BDD" });
      const tips = empty.createDiv({ cls: "buddybridge-empty-chat-tips" });
      tips.createDiv({ text: "\u{1F4A1} \u63D0\u793A" });
      const tipList = tips.createEl("ul");
      const tipItems = [
        "Shift+Enter \u6362\u884C\uFF0CEnter \u53D1\u9001",
        "\u8F93\u5165 / \u67E5\u770B\u53EF\u7528\u547D\u4EE4",
        "\u591A\u8F6E\u5BF9\u8BDD\u81EA\u52A8\u4FDD\u6301\u4E0A\u4E0B\u6587"
      ];
      for (const tip of tipItems) {
        tipList.createEl("li", { text: tip });
      }
      return;
    }
    for (const msg of conv.messages) {
      await this.renderMessage(msg, () => this.retryLastExchange());
    }
    this.scrollToBottom();
  }
  async renderMessage(msg, onRetry) {
    const row = this.messageContainer.createDiv({
      cls: `buddybridge-message-row buddybridge-message-${msg.role}`
    });
    const bubble = row.createDiv({ cls: "buddybridge-bubble" });
    const isWaiting = msg.role === "assistant" && msg.content === "" && msg.id === this.streamingMsgId;
    if (isWaiting) {
      this.renderThinkingIndicator(bubble);
    } else if (msg.role === "assistant") {
      if (msg.content.startsWith("\u9519\u8BEF:") || msg.content.startsWith("Error:")) {
        this.renderErrorCard(bubble, msg.content, onRetry);
      } else {
        if (msg.parts && msg.parts.length > 0) {
          this.renderMessageParts(bubble, msg.parts);
        }
        await this.renderMarkdownContent(bubble, msg.content);
      }
    } else {
      bubble.createSpan({ text: msg.content });
    }
    return row;
  }
  /** 从持久化的 parts 重建思考块与工具卡（流式结束后、切标签、重启后仍保留）。 */
  renderMessageParts(bubble, parts) {
    let toolsBlock = null;
    for (const part of parts) {
      if (part.kind === "thinking") {
        this.renderThinkingBlock(bubble, part.content || "", "\u5DF2\u601D\u8003");
      } else if (part.kind === "tool") {
        if (!toolsBlock) {
          toolsBlock = this.renderToolsBlock(bubble);
        }
        this.appendToolRow(toolsBlock, part.name || "", part.detail || "");
      }
    }
  }
  /** 创建/复用可折叠思考块，并更新标题与正文。 */
  renderThinkingBlock(bubble, content, label) {
    let block = bubble.querySelector(".buddybridge-thinking-block");
    if (!block) {
      block = bubble.createDiv({ cls: "buddybridge-thinking-block" });
      const header = block.createDiv({ cls: "buddybridge-thinking-header" });
      const icon = header.createSpan({ cls: "buddybridge-thinking-header-icon" });
      (0, import_obsidian.setIcon)(icon, "sparkles");
      header.createSpan({ cls: "buddybridge-thinking-header-text", text: label });
      const chevron = header.createSpan({ cls: "buddybridge-thinking-header-chevron", text: "\u25BE" });
      const bodyDiv = block.createDiv({ cls: "buddybridge-thinking-body buddybridge-hidden" });
      header.addEventListener("click", () => {
        const hidden = bodyDiv.hasClass("buddybridge-hidden");
        bodyDiv.toggleClass("buddybridge-hidden", !hidden);
        chevron.textContent = hidden ? "\u25BE" : "\u25B8";
      });
    }
    const headerText = block.querySelector(".buddybridge-thinking-header-text");
    if (headerText instanceof HTMLElement) {
      headerText.setText(label);
    }
    const body = block.querySelector(".buddybridge-thinking-body");
    if (body instanceof HTMLElement) {
      body.setText(content);
    }
    return block;
  }
  /** 创建/复用工具卡容器。 */
  renderToolsBlock(bubble) {
    let toolsBlock = bubble.querySelector(".buddybridge-tools-block");
    if (!toolsBlock) {
      toolsBlock = bubble.createDiv({ cls: "buddybridge-tools-block" });
      const hdr = toolsBlock.createDiv({ cls: "buddybridge-tools-header" });
      const icon = hdr.createSpan({ cls: "buddybridge-tools-header-icon" });
      (0, import_obsidian.setIcon)(icon, "wrench");
      hdr.createSpan({ cls: "buddybridge-tools-header-text", text: "\u5DE5\u5177\u8C03\u7528" });
      const chevron = hdr.createSpan({ cls: "buddybridge-tools-header-chevron", text: "\u25BE" });
      hdr.addEventListener("click", () => {
        const list = toolsBlock.querySelector(".buddybridge-tools-list");
        if (list instanceof HTMLElement) {
          const hidden = list.hasClass("buddybridge-hidden");
          list.toggleClass("buddybridge-hidden", !hidden);
          chevron.textContent = hidden ? "\u25BE" : "\u25B8";
        }
      });
      toolsBlock.createDiv({ cls: "buddybridge-tools-list buddybridge-hidden" });
    }
    return toolsBlock;
  }
  /** 向工具卡容器追加一行工具调用。 */
  appendToolRow(toolsBlock, toolName, toolDetail) {
    const list = toolsBlock.querySelector(".buddybridge-tools-list");
    if (!(list instanceof HTMLElement))
      return;
    let iconName = "wrench";
    if (toolName.includes("read") || toolName.includes("\u67E5\u770B") || toolName.includes("\u8BFB\u53D6")) {
      iconName = "file-text";
    } else if (toolName.includes("write") || toolName.includes("\u7F16\u8F91") || toolName.includes("\u5199\u5165")) {
      iconName = "pencil";
    } else if (toolName.includes("search") || toolName.includes("\u641C\u7D22") || toolName.includes("\u67E5\u627E")) {
      iconName = "search";
    }
    const row = list.createDiv({ cls: "buddybridge-tool-call" });
    const icon = row.createSpan({ cls: "buddybridge-tool-call-icon" });
    (0, import_obsidian.setIcon)(icon, iconName);
    row.createSpan({
      cls: "buddybridge-tool-call-text",
      text: `${toolName} ${toolDetail}`.trim()
    });
  }
  /**
   * 错误卡「重试」（P0.3）：删除最近一对 user+assistant 消息（失败的那对），
   * 将 user 消息放回输入框并自动重发。超时/致命错误均可触发。
   */
  retryLastExchange() {
    const conv = this.manager.getActive();
    if (!conv || conv.messages.length === 0)
      return;
    let lastUserIdx = -1;
    for (let i = conv.messages.length - 1; i >= 0; i--) {
      if (conv.messages[i].role === "user") {
        lastUserIdx = i;
        break;
      }
    }
    if (lastUserIdx < 0)
      return;
    const userMsg = conv.messages[lastUserIdx];
    const idsToRemove = conv.messages.slice(lastUserIdx).map((m) => m.id);
    this.manager.removeMessages(conv.id, idsToRemove);
    this.inputEl.value = userMsg.content;
    this.adjustTextareaHeight();
    void this.renderMessages();
    void this.sendMessage();
  }
  renderErrorCard(bubble, content, onRetry) {
    const card = bubble.createDiv({ cls: "buddybridge-error-card" });
    const icon = card.createDiv({ cls: "buddybridge-error-card-icon" });
    (0, import_obsidian.setIcon)(icon, "alert-triangle");
    const errorMsg = content.replace(/^错误:\s*/, "").replace(/^Error:\s*/, "");
    card.createDiv({ cls: "buddybridge-error-card-title", text: "\u8BF7\u6C42\u5931\u8D25" });
    card.createDiv({ cls: "buddybridge-error-card-body", text: errorMsg });
    const hint = this.getErrorHint(errorMsg);
    if (hint) {
      card.createDiv({ cls: "buddybridge-error-card-hint", text: hint });
    }
    if (onRetry) {
      const actions = card.createDiv({ cls: "buddybridge-error-card-actions" });
      const retryBtn = actions.createEl("button", {
        text: "\u91CD\u8BD5",
        cls: "mod-cta buddybridge-error-retry-btn",
        attr: { "aria-label": "\u91CD\u8BD5\u4E0A\u6B21\u53D1\u9001" }
      });
      retryBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        onRetry();
      };
    }
  }
  getErrorHint(errorMsg) {
    if (errorMsg.includes("\u627E\u4E0D\u5230 codebuddy") || errorMsg.includes("ENOENT") || errorMsg.includes("codebuddy")) {
      return "\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u6307\u5B9A\u6B63\u786E\u7684 CodeBuddy \u8DEF\u5F84\uFF0C\u6216\u786E\u8BA4\u5DF2\u5B89\u88C5 WorkBuddy \u684C\u9762\u7248\u3002";
    }
    if (errorMsg.includes("Node.js") || errorMsg.includes("node")) {
      return "\u8BF7\u786E\u8BA4 Node.js \u5DF2\u6B63\u786E\u5B89\u88C5\uFF0C\u6216\u8FD0\u884C\u73AF\u5883\u521D\u59CB\u5316\u63D0\u793A\u8BCD\u3002";
    }
    if (errorMsg.includes("timeout") || errorMsg.includes("\u8D85\u65F6") || errorMsg.includes("TIMEOUT")) {
      return "\u8BF7\u6C42\u8D85\u65F6\uFF0C\u8BF7\u91CD\u8BD5\u3002";
    }
    return null;
  }
  renderThinkingIndicator(bubble) {
    const thinking = bubble.createDiv({ cls: "buddybridge-thinking" });
    thinking.createSpan({ cls: "buddybridge-thinking-text", text: "\u601D\u8003\u4E2D" });
    const dots = thinking.createDiv({ cls: "buddybridge-thinking-dots" });
    for (let i = 0; i < 3; i++) {
      dots.createSpan({ cls: "buddybridge-dot" });
    }
  }
  async renderMarkdownContent(bubble, content) {
    if (!content)
      return;
    const thinkingBlock = bubble.querySelector(".buddybridge-thinking-block");
    const toolsBlock = bubble.querySelector(".buddybridge-tools-block");
    let markdownContainer = bubble.querySelector(".buddybridge-markdown-content");
    if (!(markdownContainer instanceof HTMLElement)) {
      markdownContainer = bubble.createDiv({ cls: "buddybridge-markdown-content" });
      if (thinkingBlock instanceof HTMLElement) {
        bubble.insertBefore(markdownContainer, thinkingBlock);
      } else if (toolsBlock instanceof HTMLElement) {
        bubble.insertBefore(markdownContainer, toolsBlock);
      }
    }
    if (!(markdownContainer instanceof HTMLElement))
      return;
    markdownContainer.empty();
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      content,
      markdownContainer,
      "",
      this.markdownComponent
    );
    this.linkFileReferences(markdownContainer);
  }
  /** 构建/复用 vault 文件索引（带过期时间，避免每次渲染都重建） */
  getFileIndex() {
    const now = Date.now();
    if (this.fileIndex && now - this.fileIndexBuiltAt < 1e4) {
      return this.fileIndex;
    }
    const paths = /* @__PURE__ */ new Map();
    const basenames = /* @__PURE__ */ new Map();
    for (const file of this.app.vault.getFiles()) {
      const normalized = file.path.toLowerCase().replace(/\\/g, "/");
      paths.set(normalized, file.path);
      const key = (file.basename + "." + file.extension).toLowerCase();
      const list = basenames.get(key);
      if (list) {
        list.push(file.path);
      } else {
        basenames.set(key, [file.path]);
      }
    }
    this.fileIndex = { paths, basenames };
    this.fileIndexBuiltAt = now;
    return this.fileIndex;
  }
  /** 遍历 markdown 容器，把文件名文本节点替换为可点击链接 */
  linkFileReferences(container) {
    const index = this.getFileIndex();
    const walker = document.createTreeWalker(
      container,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode: (node) => {
          const parent = node.parentElement;
          if (!parent)
            return NodeFilter.FILTER_REJECT;
          if (parent.closest("a"))
            return NodeFilter.FILTER_REJECT;
          if (parent.closest("pre"))
            return NodeFilter.FILTER_REJECT;
          return NodeFilter.FILTER_ACCEPT;
        }
      }
    );
    const textNodes = [];
    while (walker.nextNode()) {
      textNodes.push(walker.currentNode);
    }
    for (const node of textNodes) {
      this.linkTextNode(node, index);
    }
  }
  /** 解析候选词：优先全路径匹配，其次唯一文件名匹配 */
  resolveFilePath(token, index) {
    const normalized = token.toLowerCase().replace(/\\/g, "/");
    const full = index.paths.get(normalized);
    if (full)
      return full;
    const sep = Math.max(normalized.lastIndexOf("/"), normalized.lastIndexOf("\\"));
    const base = sep >= 0 ? normalized.slice(sep + 1) : normalized;
    const list = index.basenames.get(base);
    if (list && list.length === 1)
      return list[0];
    return null;
  }
  /** 把单个文本节点中匹配到的文件名替换为可点击链接 */
  linkTextNode(node, index) {
    var _a;
    const raw = node.nodeValue || "";
    if (!raw)
      return;
    const re = /[\u4e00-\u9fff\u3400-\u4dbf\w./\\-]+/g;
    const matches = [];
    let m;
    while ((m = re.exec(raw)) !== null) {
      const token = m[0].replace(/[.,;:!?)\]}>'"。，；：！？）】》’"」》]+$/, "");
      if (!token)
        continue;
      const resolved = this.resolveFilePath(token, index);
      if (resolved) {
        matches.push({ start: m.index, end: m.index + token.length, path: resolved });
      }
    }
    if (matches.length === 0)
      return;
    const frag = document.createDocumentFragment();
    let cursor = 0;
    for (const match of matches) {
      if (match.start > cursor) {
        frag.append(document.createTextNode(raw.slice(cursor, match.start)));
      }
      const link = document.createElement("a");
      link.addClass("internal-link");
      link.setAttribute("data-href", match.path);
      link.setAttribute("href", match.path);
      link.textContent = raw.slice(match.start, match.end);
      link.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void this.app.workspace.openLinkText(match.path, "");
      });
      frag.append(link);
      cursor = match.end;
    }
    if (cursor < raw.length) {
      frag.append(document.createTextNode(raw.slice(cursor)));
    }
    (_a = node.parentNode) == null ? void 0 : _a.replaceChild(frag, node);
  }
  adjustTextareaHeight() {
    this.inputEl.style.setProperty("--buddybridge-input-height", `${this.inputEl.scrollHeight}px`);
  }
  setInputEnabled(enabled) {
    this.inputEl.disabled = !enabled;
    this.sendBtn.disabled = false;
    this.sendBtn.setText(enabled ? "\u53D1\u9001" : "\u505C\u6B62");
    this.sendBtn.toggleClass("buddybridge-send-btn-stop", !enabled);
  }
  stopStreaming() {
    this.stopRequested = true;
    this.api.cancel();
  }
  updateCommandDropdown() {
    const val = this.inputEl.value;
    if (val === "/") {
      if (!this.commandDropdown) {
        const parent = this.inputEl.parentElement;
        if (!parent)
          return;
        this.commandDropdown = parent.createDiv({ cls: "buddybridge-command-dropdown" });
        for (const [cmd, desc] of Object.entries(COMMANDS)) {
          const item = this.commandDropdown.createDiv({ cls: "buddybridge-command-item" });
          item.createSpan({ cls: "buddybridge-command-name", text: cmd });
          item.createSpan({ cls: "buddybridge-command-desc", text: desc });
          item.onclick = () => {
            this.inputEl.value = cmd + " ";
            this.inputEl.focus();
            this.removeCommandDropdown();
          };
        }
      }
    } else {
      this.removeCommandDropdown();
    }
  }
  removeCommandDropdown() {
    if (this.commandDropdown) {
      this.commandDropdown.remove();
      this.commandDropdown = null;
    }
  }
  async handleKeydown(e) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      await this.sendMessage();
    }
    if (e.key === "Escape") {
      this.removeCommandDropdown();
    }
  }
  async sendMessage() {
    const activeConv = this.manager.getActive();
    if (activeConv && this.streamingConversations.has(activeConv.id))
      return;
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    if (text.startsWith("/")) {
      const cmd = text.split(" ")[0].toLowerCase();
      if (cmd === "/clear") {
        this.createNewChat();
        return;
      }
    }
    let conv = this.manager.getActive();
    if (!conv) {
      conv = this.manager.createConversation();
      this.renderTabs();
    }
    if (!conv.sessionId) {
      conv.sessionId = this.api.generateId();
    }
    const convId = conv.id;
    this.manager.addMessage(convId, "user", text);
    this.inputEl.value = "";
    this.adjustTextareaHeight();
    await this.renderMessages();
    const aiMsg = this.manager.addMessage(convId, "assistant", "");
    if (!aiMsg)
      return;
    this.streamingMsgId = aiMsg.id;
    this.streamingConversations.add(convId);
    this.setInputEnabled(false);
    await this.renderMessages();
    let firstChunk = true;
    let thinkingContent = "";
    let textContent = "";
    let parts = [];
    let streamingError = null;
    try {
      const contextText = text.startsWith("/") ? text : this.buildContextText(convId, text);
      const streamingBubble = this.messageContainer.querySelector(
        `.buddybridge-message-assistant:last-child .buddybridge-bubble`
      );
      if (!(streamingBubble instanceof HTMLElement)) {
        throw new Error("\u627E\u4E0D\u5230 Assistant \u6D88\u606F\u6C14\u6CE1");
      }
      for await (const chunk of this.api.sendMessage(conv.sessionId, contextText, this.vaultPath)) {
        const bubble = streamingBubble;
        const hasRealContent = textContent.length > 0 || thinkingContent.length > 0 || parts.length > 0;
        if (chunk.type === "text" && !hasRealContent && isStartupBanner(chunk.content)) {
          continue;
        }
        if (firstChunk) {
          firstChunk = false;
          const thinking = bubble.querySelector(".buddybridge-thinking");
          if (thinking instanceof HTMLElement) {
            thinking.addClass("buddybridge-thinking-fadeout");
            await new Promise((r) => window.setTimeout(r, 200));
            thinking.remove();
          }
        }
        if (chunk.type === "thinking") {
          thinkingContent += chunk.content;
          const lastPart = parts[parts.length - 1];
          if (lastPart && lastPart.kind === "thinking") {
            lastPart.content = thinkingContent;
          } else {
            parts.push({ kind: "thinking", content: thinkingContent });
          }
          this.manager.updateMessageParts(convId, aiMsg.id, parts, true);
          this.renderThinkingBlock(bubble, thinkingContent, "\u601D\u8003\u4E2D...");
        } else if (chunk.type === "tool") {
          parts.push({ kind: "tool", name: chunk.toolName || "", detail: chunk.toolDetail || "" });
          this.manager.updateMessageParts(convId, aiMsg.id, parts, true);
          const toolsBlock = this.renderToolsBlock(bubble);
          this.appendToolRow(toolsBlock, chunk.toolName || "", chunk.toolDetail || "");
        } else if (chunk.type === "text") {
          textContent += chunk.content;
          this.manager.updateMessage(convId, aiMsg.id, textContent, true);
          await this.renderMarkdownContent(bubble, textContent);
        } else if (chunk.type === "error") {
          streamingError = chunk.content;
          this.manager.updateMessage(convId, aiMsg.id, `\u9519\u8BEF: ${chunk.content}`, true);
          new import_obsidian.Notice(`\u8BF7\u6C42\u5931\u8D25: ${chunk.content}`);
        }
      }
      if (streamingError) {
        this.manager.updateMessage(convId, aiMsg.id, `\u9519\u8BEF: ${streamingError}`);
        this.manager.updateMessageParts(convId, aiMsg.id, void 0, true);
      } else {
        this.manager.updateMessage(convId, aiMsg.id, textContent);
        const hasContent = Boolean(textContent || thinkingContent || parts.length > 0);
        if (!hasContent) {
          this.manager.updateMessage(convId, aiMsg.id, this.stopRequested ? "\uFF08\u5DF2\u505C\u6B62\uFF09" : "\uFF08\u65E0\u54CD\u5E94\uFF0C\u8BF7\u91CD\u8BD5\uFF09");
        } else if (this.stopRequested && textContent) {
          this.manager.updateMessage(convId, aiMsg.id, textContent + "\n\n\uFF08\u5DF2\u505C\u6B62\uFF09");
        }
      }
      await this.renderMessages();
      await this.manager.flush();
    } catch (error) {
      const message = getErrorMessage(error);
      this.manager.updateMessage(convId, aiMsg.id, `\u9519\u8BEF: ${message}`);
      new import_obsidian.Notice(`\u8BF7\u6C42\u5931\u8D25: ${message}`);
      await this.renderMessages();
    } finally {
      this.streamingConversations.delete(convId);
      this.streamingMsgId = null;
      this.stopRequested = false;
      this.setInputEnabled(true);
    }
  }
  updateCurrentFileBar() {
    const file = this.app.workspace.getActiveFile();
    if (file) {
      this.currentFileBar.setText(`\u{1F4C4} ${file.path}`);
    } else {
      this.currentFileBar.setText("");
    }
  }
  scrollToBottom() {
    this.messageContainer.scrollTop = this.messageContainer.scrollHeight;
  }
};

// src/settings/tab.ts
var import_obsidian3 = require("obsidian");

// src/settings/confirm.ts
var import_obsidian2 = require("obsidian");
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("p", { text: this.message, cls: "buddybridge-confirm-message" });
    const actions = contentEl.createDiv({ cls: "buddybridge-confirm-actions" });
    const cancelBtn = actions.createEl("button", { text: "\u53D6\u6D88", cls: "mod-cta" });
    cancelBtn.onclick = () => this.close();
    const okBtn = actions.createEl("button", { text: "\u786E\u8BA4", cls: "mod-warning" });
    okBtn.onclick = async () => {
      await this.onConfirm();
      this.close();
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings/tab.ts
var BuddyBridgeSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const plugin = this.plugin;
    new import_obsidian3.Setting(containerEl).setName("\u8FDE\u63A5\u914D\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("CodeBuddy \u8DEF\u5F84").setDesc("codebuddy \u53EF\u6267\u884C\u6587\u4EF6\u8DEF\u5F84\u3002\u5982 WorkBuddy \u81EA\u5B9A\u4E49\u5B89\u88C5\uFF0C\u8DEF\u5F84\u901A\u5E38\u4E3A\uFF1A\u5B89\u88C5\u76EE\u5F55\\resources\\app.asar.unpacked\\cli\\bin\\codebuddy\uFF08\u53F3\u952E WorkBuddy \u5FEB\u6377\u65B9\u5F0F \u2192 \u6253\u5F00\u6587\u4EF6\u4F4D\u7F6E \u53EF\u627E\u5230\u5B89\u88C5\u76EE\u5F55\uFF09").addText((text) => text.setPlaceholder("WorkBuddy\u5B89\u88C5\u76EE\u5F55\\resources\\app.asar.unpacked\\cli\\bin\\codebuddy").setValue(plugin.settings.codebuddyPath).onChange(async (value) => {
      plugin.settings.codebuddyPath = value;
      plugin.api.setCodebuddyPath(value);
      await plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Node \u8DEF\u5F84\uFF08\u53EF\u9009\uFF09").setDesc("\u7559\u7A7A\u81EA\u52A8\u68C0\u6D4B\u3002\u4EC5\u5F53\u4EE5\u7EAF\u811A\u672C\u65B9\u5F0F\u542F\u52A8 codebuddy\uFF08\u975E .exe/.cmd\uFF09\u65F6\u4F7F\u7528\u3002").addText((text) => text.setPlaceholder("\u81EA\u52A8\u68C0\u6D4B").setValue(plugin.settings.nodePath).onChange(async (value) => {
      plugin.settings.nodePath = value;
      plugin.api.setNodePath(value);
      await plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("CLI \u8D85\u65F6\u65F6\u957F\uFF08\u79D2\uFF09").setDesc("\u8BF7\u6C42\u8D85\u8FC7\u8BE5\u65F6\u957F\u672A\u6536\u5230\u5B8C\u6574\u56DE\u590D\u65F6\u81EA\u52A8\u7EC8\u6B62\u5E76\u63D0\u793A\uFF08\u9ED8\u8BA4 300 \u79D2\uFF09").addText((text) => text.setPlaceholder("300").setValue(String(plugin.settings.timeoutSeconds)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        plugin.settings.timeoutSeconds = num;
        await plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u4E0A\u4E0B\u6587\u6CE8\u5165").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u6CE8\u5165\u5F53\u524D\u7B14\u8BB0\u94FE\u63A5").setDesc("\u53D1\u9001\u6D88\u606F\u65F6\u81EA\u52A8\u5728\u6D88\u606F\u524D\u9644\u52A0 [\u5F53\u524D\u7B14\u8BB0: \u8DEF\u5F84]\uFF0C\u8BA9 AI \u77E5\u9053\u4F60\u5728\u770B\u54EA\u4E2A\u7B14\u8BB0\uFF08\u9ED8\u8BA4\u5F00\u542F\uFF09").addToggle((toggle) => toggle.setValue(plugin.settings.noteLinkInjection).onChange(async (value) => {
      plugin.settings.noteLinkInjection = value;
      await plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6CE8\u5165 Vault \u4E0A\u4E0B\u6587").setDesc("\u989D\u5916\u9644\u52A0 [Vault: \u4ED3\u5E93\u6839\u8DEF\u5F84]\uFF0C\u5E2E\u52A9 AI \u7406\u89E3\u7B14\u8BB0\u6240\u5728\u7684\u4ED3\u5E93\uFF08\u9ED8\u8BA4\u5173\u95ED\uFF09").addToggle((toggle) => toggle.setValue(plugin.settings.vaultContextInjection).onChange(async (value) => {
      plugin.settings.vaultContextInjection = value;
      await plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5916\u89C2").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u4E3B\u8272\u8C03").setDesc("\u804A\u5929\u9762\u677F\u7684\u4E3B\u9898\u8272\u3002\u7559\u7A7A\u4F7F\u7528 Obsidian \u9ED8\u8BA4\u5F3A\u8C03\u8272\u3002").addText((text) => {
      text.inputEl.type = "color";
      text.setValue(plugin.settings.primaryColor || "#8b5cf6");
      text.onChange(async (value) => {
        plugin.settings.primaryColor = value;
        await plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("\u7BA1\u7406").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u6700\u5927\u5BF9\u8BDD\u6570").setDesc("\u6700\u591A\u4FDD\u7559\u591A\u5C11\u4E2A\u5BF9\u8BDD\uFF08\u8D85\u51FA\u90E8\u5206\u81EA\u52A8\u5220\u9664\uFF09").addText((text) => text.setPlaceholder("20").setValue(String(plugin.settings.maxConversations)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        plugin.settings.maxConversations = num;
        await plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5BFC\u51FA\u8BBE\u7F6E\uFF08\u542B\u804A\u5929\u8BB0\u5F55\uFF09").setDesc("\u5C06\u5168\u90E8\u8BBE\u7F6E\u4E0E\u804A\u5929\u8BB0\u5F55\u5BFC\u51FA\u4E3A\u5E26\u7248\u672C\u53F7\u7684 JSON \u6587\u4EF6\uFF0C\u7528\u4E8E\u5907\u4EFD\u6216\u8FC1\u79FB").addButton((btn) => btn.setButtonText("\u5BFC\u51FA").onClick(async () => {
      await plugin.exportData();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5BFC\u5165\u8BBE\u7F6E\uFF08\u542B\u804A\u5929\u8BB0\u5F55\uFF09").setDesc("\u4ECE JSON \u6587\u4EF6\u6062\u590D\u8BBE\u7F6E\u4E0E\u804A\u5929\u8BB0\u5F55\uFF08\u4F1A\u8986\u76D6\u5F53\u524D\u6570\u636E\uFF0C\u9700\u4E8C\u6B21\u786E\u8BA4\uFF09").addButton((btn) => {
      btn.setButtonText("\u5BFC\u5165");
      btn.buttonEl.addEventListener("click", (evt) => {
        evt.preventDefault();
        evt.stopPropagation();
        void plugin.importDataFromFile();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("\u91CD\u7F6E\u4E3A\u9ED8\u8BA4").setDesc("\u5C06\u6240\u6709\u8BBE\u7F6E\u6062\u590D\u4E3A\u9ED8\u8BA4\u503C\uFF08\u4E0D\u4F1A\u5220\u9664\u804A\u5929\u8BB0\u5F55\uFF0C\u9700\u4E8C\u6B21\u786E\u8BA4\uFF09").addButton((btn) => btn.setButtonText("\u91CD\u7F6E").onClick(() => {
      new ConfirmModal(
        this.app,
        "\u786E\u8BA4\u5C06\u6240\u6709\u8BBE\u7F6E\u6062\u590D\u4E3A\u9ED8\u8BA4\u503C\uFF1F\u804A\u5929\u8BB0\u5F55\u5C06\u4FDD\u7559\u3002",
        async () => {
          plugin.settings = { ...DEFAULT_SETTINGS };
          plugin.api.setCodebuddyPath("");
          plugin.api.setNodePath("");
          await plugin.saveSettings();
          new import_obsidian3.Notice("\u8BBE\u7F6E\u5DF2\u91CD\u7F6E\u4E3A\u9ED8\u8BA4");
          this.display();
        }
      ).open();
    }));
  }
};

// src/io.ts
var EXPORT_FORMAT = "buddybridge-export";
var EXPORT_VERSION = 1;
function buildExportPayload(settings, conversations) {
  return {
    format: EXPORT_FORMAT,
    exportVersion: EXPORT_VERSION,
    dataVersion: DATA_VERSION,
    exportedAt: Date.now(),
    settings: migrateSettings(settings),
    conversations: (conversations || []).map((c) => normalizeConversation(c)).filter((c) => c !== null)
  };
}
function serializeExport(payload) {
  return JSON.stringify(payload, null, 2);
}
function validateExport(raw) {
  var _a;
  if (!isObject(raw))
    return null;
  if (raw.format !== EXPORT_FORMAT)
    return null;
  if (getNumber(raw, "exportVersion") !== EXPORT_VERSION)
    return null;
  const dataVersion = getNumber(raw, "dataVersion");
  if (typeof dataVersion !== "number" || dataVersion < 1)
    return null;
  const settings = isObject(raw.settings) ? migrateSettings(raw.settings) : migrateSettings(null);
  const rawConvs = raw.conversations;
  const conversations = Array.isArray(rawConvs) ? rawConvs.map((c) => normalizeConversation(c)).filter((c) => c !== null) : [];
  return {
    format: EXPORT_FORMAT,
    exportVersion: EXPORT_VERSION,
    dataVersion,
    exportedAt: (_a = getNumber(raw, "exportedAt")) != null ? _a : Date.now(),
    settings,
    conversations
  };
}
function parseExport(json) {
  try {
    return validateExport(JSON.parse(json));
  } catch (e) {
    return null;
  }
}
function downloadJSONFile(filename, content) {
  const blob = new Blob([content], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.classList.add("buddybridge-helper-hidden");
  document.body.appendChild(a);
  a.click();
  if (a.parentElement)
    a.remove();
  URL.revokeObjectURL(url);
}
function pickJSONViaElectron() {
  return new Promise((resolve) => {
    var _a;
    try {
      const w = window;
      if (typeof w.require !== "function") {
        resolve(null);
        return;
      }
      const electron = w.require("electron");
      const remote = electron == null ? void 0 : electron.remote;
      const dialog = (_a = remote == null ? void 0 : remote.dialog) != null ? _a : electron == null ? void 0 : electron.dialog;
      if (!dialog) {
        resolve(null);
        return;
      }
      const win = (remote == null ? void 0 : remote.getCurrentWindow) ? remote.getCurrentWindow() : null;
      const opts = { properties: ["openFile"], filters: [{ name: "JSON", extensions: ["json"] }] };
      const p = win ? dialog.showOpenDialog(win, opts) : dialog.showOpenDialog(opts);
      if (!p || typeof p.then !== "function") {
        resolve(null);
        return;
      }
      p.then(async (result) => {
        const r = result;
        const filePath = Array.isArray(r == null ? void 0 : r.filePaths) && r.filePaths.length > 0 ? r.filePaths[0] : "";
        if (!filePath) {
          resolve("");
          return;
        }
        try {
          const fs2 = w.require("fs");
          const content = await fs2.promises.readFile(filePath, "utf-8");
          resolve(String(content));
        } catch (e) {
          resolve(null);
        }
      }).catch(() => resolve(null));
    } catch (e) {
      resolve(null);
    }
  });
}
function pickJSONViaDomInput() {
  return new Promise((resolve, reject) => {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = ".json,application/json";
    input.classList.add("buddybridge-helper-hidden");
    document.body.appendChild(input);
    let safetyTimer = 0;
    const cleanup = () => {
      if (safetyTimer)
        window.clearTimeout(safetyTimer);
      if (input.parentElement)
        input.remove();
    };
    const finish = (value) => {
      cleanup();
      resolve(value);
    };
    const fail = (err) => {
      cleanup();
      reject(err);
    };
    input.onchange = () => {
      var _a;
      const file = (_a = input.files) == null ? void 0 : _a[0];
      if (!file) {
        finish("");
        return;
      }
      const reader = new FileReader();
      reader.onload = () => {
        var _a2;
        return finish(String((_a2 = reader.result) != null ? _a2 : ""));
      };
      reader.onerror = () => fail(new Error("\u8BFB\u53D6\u6587\u4EF6\u5931\u8D25"));
      reader.readAsText(file);
    };
    input.oncancel = () => finish("");
    safetyTimer = window.setTimeout(() => finish(""), 6e4);
    input.click();
  });
}
async function pickAndReadJSONFile() {
  const viaElectron = await pickJSONViaElectron();
  if (viaElectron !== null)
    return viaElectron;
  return pickJSONViaDomInput();
}

// src/main.ts
var BuddyBridgePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.chatView = null;
  }
  async onload() {
    try {
      await this.loadSettings();
      this.api = new BuddyBridgeAPI();
      this.api.setCodebuddyPath(this.settings.codebuddyPath);
      this.api.setNodePath(this.settings.nodePath);
      this.api.setTimeoutMs(this.settings.timeoutSeconds * 1e3);
      this.registerView(
        VIEW_TYPE_CHAT,
        (leaf) => {
          const view = new BuddyBridgeChatView(leaf, this.api, async () => {
            const data = normalizePersistedData(await this.loadData());
            return data.conversations || [];
          });
          this.chatView = view;
          view.getManager().setPersistCallback(async (conversations) => {
            const data = normalizePersistedData(await this.loadData());
            data.conversations = conversations;
            await this.saveData(data);
          });
          return view;
        }
      );
      this.addRibbonIcon("bot", "BuddyBridge \u804A\u5929", async () => {
        await this.activateView();
      });
      this.addCommand({
        id: "open-chat",
        name: "\u6253\u5F00\u804A\u5929\u9762\u677F",
        callback: async () => {
          await this.activateView();
        }
      });
      this.addSettingTab(new BuddyBridgeSettingTab(this.app, this));
      this.applyPrimaryColor();
    } catch (e) {
      console.error("[BB] \u63D2\u4EF6\u52A0\u8F7D\u5931\u8D25:", e);
      new import_obsidian4.Notice("BuddyBridge \u52A0\u8F7D\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B Console");
    }
  }
  onunload() {
    this.api.cancel();
  }
  async activateView() {
    try {
      const { workspace } = this.app;
      let leaf = workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
      if (!leaf) {
        leaf = workspace.getRightLeaf(true);
        if (!leaf) {
          leaf = workspace.getLeaf(true);
        }
        if (leaf) {
          await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
        }
      }
      if (leaf) {
        await workspace.revealLeaf(leaf);
        workspace.setActiveLeaf(leaf, { focus: true });
      } else {
        new import_obsidian4.Notice("BuddyBridge\uFF1A\u65E0\u6CD5\u521B\u5EFA\u804A\u5929\u9762\u677F");
      }
    } catch (e) {
      console.error("[BB] \u6253\u5F00\u804A\u5929\u9762\u677F\u5931\u8D25:", e);
      new import_obsidian4.Notice("BuddyBridge\uFF1A\u6253\u5F00\u9762\u677F\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B Console");
    }
  }
  async loadSettings() {
    const data = normalizePersistedData(await this.loadData());
    this.settings = migrateSettings(data.settings);
  }
  async saveSettings() {
    const existingData = normalizePersistedData(await this.loadData());
    const merged = { ...existingData, settings: this.settings };
    await this.saveData(merged);
    this.api.setCodebuddyPath(this.settings.codebuddyPath);
    this.api.setNodePath(this.settings.nodePath);
    this.api.setTimeoutMs(this.settings.timeoutSeconds * 1e3);
    if (this.chatView) {
      this.chatView.getManager().setMaxConversations(this.settings.maxConversations);
    }
    this.applyPrimaryColor();
  }
  // ==================== 导出 / 导入（P2.6）====================
  /** 导出设置 + 聊天记录为带版本号的 JSON 文件。 */
  async exportData() {
    var _a, _b;
    try {
      const data = normalizePersistedData(await this.loadData());
      const payload = buildExportPayload((_a = data.settings) != null ? _a : {}, (_b = data.conversations) != null ? _b : []);
      const json = serializeExport(payload);
      const stamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      downloadJSONFile(`buddybridge-backup-${stamp}.json`, json);
      new import_obsidian4.Notice("\u5DF2\u5BFC\u51FA\u8BBE\u7F6E\u4E0E\u804A\u5929\u8BB0\u5F55");
    } catch (e) {
      console.error("[BB] \u5BFC\u51FA\u5931\u8D25:", e);
      new import_obsidian4.Notice(`\u5BFC\u51FA\u5931\u8D25\uFF1A${getErrorMessage(e)}`);
    }
  }
  /** 弹出文件选择框 → 解析校验 → 二次确认后导入。 */
  async importDataFromFile() {
    try {
      const json = await pickAndReadJSONFile();
      if (!json)
        return;
      const payload = parseExport(json);
      if (!payload) {
        new import_obsidian4.Notice("\u5BFC\u5165\u5931\u8D25\uFF1A\u6587\u4EF6\u683C\u5F0F\u4E0D\u6B63\u786E\uFF0C\u6216\u5BFC\u51FA\u7248\u672C\u4E0E\u672C\u63D2\u4EF6\u4E0D\u517C\u5BB9");
        return;
      }
      new ConfirmModal(
        this.app,
        `\u5BFC\u5165\u5C06\u8986\u76D6\u5F53\u524D\u8BBE\u7F6E\u4E0E ${payload.conversations.length} \u6761\u804A\u5929\u8BB0\u5F55\uFF0C\u662F\u5426\u7EE7\u7EED\uFF1F`,
        async () => {
          await this.importData(payload);
          new import_obsidian4.Notice("\u5BFC\u5165\u6210\u529F");
        }
      ).open();
    } catch (e) {
      console.error("[BB] \u5BFC\u5165\u5931\u8D25:", e);
      new import_obsidian4.Notice(`\u5BFC\u5165\u5931\u8D25\uFF1A${getErrorMessage(e)}`);
    }
  }
  /** 应用已校验的导出数据：覆盖设置与聊天记录，并刷新 API 与聊天视图。 */
  async importData(payload) {
    const data = normalizePersistedData(await this.loadData());
    data.settings = payload.settings;
    data.conversations = payload.conversations;
    await this.saveData(data);
    this.settings = migrateSettings(payload.settings);
    this.api.setCodebuddyPath(this.settings.codebuddyPath);
    this.api.setNodePath(this.settings.nodePath);
    this.api.setTimeoutMs(this.settings.timeoutSeconds * 1e3);
    this.applyPrimaryColor();
    if (this.chatView) {
      await this.chatView.loadConversations(payload.conversations);
    }
  }
  applyPrimaryColor() {
    try {
      const value = this.settings.primaryColor || "var(--interactive-accent)";
      const containers = document.querySelectorAll(".buddybridge-chat-container");
      containers.forEach((container) => {
        if (container instanceof HTMLElement) {
          container.setCssProps({ "--buddybridge-primary": value });
        }
      });
    } catch (e) {
      console.error("[BB] \u5E94\u7528\u4E3B\u8272\u8C03\u5931\u8D25:", e);
    }
  }
};
