/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BuddyBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/api.ts
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var TIMEOUT = 12e4;
function resolveCodebuddyPath() {
  if (process.env.CODEBUDDY_PATH) {
    return process.env.CODEBUDDY_PATH;
  }
  const localAppData = process.env.LOCALAPPDATA || "";
  const defaultPath = path.join(
    localAppData,
    "Programs",
    "WorkBuddy",
    "resources",
    "app.asar.unpacked",
    "cli",
    "bin",
    "codebuddy"
  );
  if (fs.existsSync(defaultPath)) {
    return defaultPath;
  }
  return "codebuddy";
}
var CODEBUDDY = resolveCodebuddyPath();
var BuddyBridgeAPI = class {
  constructor(url, timeout = TIMEOUT) {
    this.rid = 1;
    this.url = url;
    this.timeout = timeout;
  }
  setGatewayUrl(u) {
    this.url = u;
  }
  generateId() {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = Math.random() * 16 | 0;
      const v = c === "x" ? r : r & 3 | 8;
      return v.toString(16);
    });
  }
  async *sendMessage(_sessionId, text) {
    const scriptPath = CODEBUDDY;
    let resolveNext = null;
    let done = false;
    const proc = (0, import_child_process.spawn)("node", [scriptPath, text], {
      timeout: this.timeout,
      stdio: ["ignore", "pipe", "pipe"]
    });
    let out = "";
    let errOut = "";
    proc.stdout.on("data", (d) => {
      const s = d.toString();
      out += s;
      console.log("[BB] stdout:", s);
      if (resolveNext) {
        resolveNext({ value: s, done: false });
        resolveNext = null;
      }
    });
    proc.stderr.on("data", (d) => {
      errOut += d.toString();
      console.log("[BB] stderr:", errOut);
    });
    proc.on("close", (code) => {
      console.log("[BB] exit:", code, "| err:", errOut.substring(0, 200));
      done = true;
      if (errOut && !out) {
        const next = resolveNext;
        if (next) {
          next({ value: void 0, done: true });
          resolveNext = null;
        }
      } else if (resolveNext) {
        resolveNext({ value: out, done: true });
        resolveNext = null;
      }
    });
    proc.on("error", (e) => {
      console.log("[BB] spawn err:", e.message);
      done = true;
      if (resolveNext) {
        resolveNext({ value: void 0, done: true });
        resolveNext = null;
      }
    });
    while (true) {
      if (done) {
        if (errOut && !out) {
          throw new Error(errOut);
        }
        if (out) {
          yield out;
          break;
        }
        break;
      }
      const next = await new Promise((r) => {
        resolveNext = r;
      });
      if (next.done)
        break;
      yield next.value;
    }
  }
  cancel() {
  }
};

// src/views/chat.ts
var import_obsidian = require("obsidian");

// src/chat/manager.ts
var ConversationManager = class {
  constructor() {
    this.conversations = /* @__PURE__ */ new Map();
    this.activeId = null;
    this.persistCallback = null;
  }
  setPersistCallback(callback) {
    this.persistCallback = callback;
  }
  async save() {
    if (this.persistCallback) {
      await this.persistCallback(this.getAll());
    }
  }
  /** 从持久化数据加载对话 */
  load(conversations) {
    if (!conversations || conversations.length === 0) {
      this.createConversation();
      return;
    }
    for (const conv of conversations) {
      this.conversations.set(conv.id, { ...conv });
    }
    this.activeId = conversations[0].id;
  }
  /** 创建新对话 */
  createConversation(title) {
    const id = this.generateId();
    const conv = {
      id,
      title: title || "\u65B0\u5BF9\u8BDD",
      sessionId: "",
      // 首次发送消息时由 Gateway 分配
      messages: [],
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    this.conversations.set(id, conv);
    this.activeId = id;
    this.save();
    return conv;
  }
  /** 删除对话 */
  deleteConversation(id) {
    if (!this.conversations.has(id))
      return false;
    this.conversations.delete(id);
    if (this.activeId === id) {
      const remaining = this.getAll();
      this.activeId = remaining.length > 0 ? remaining[0].id : null;
    }
    this.save();
    return true;
  }
  /** 切换到指定对话 */
  switchTo(id) {
    const conv = this.conversations.get(id);
    if (!conv)
      return null;
    this.activeId = id;
    return conv;
  }
  /** 获取当前活跃对话 */
  getActive() {
    if (!this.activeId)
      return null;
    return this.conversations.get(this.activeId) || null;
  }
  /** 获取所有对话（按更新时间倒序） */
  getAll() {
    return Array.from(this.conversations.values()).sort((a, b) => b.updatedAt - a.updatedAt);
  }
  /** 添加消息到当前活跃对话 */
  addMessage(convId, role, content) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return null;
    const msg = {
      id: this.generateId(),
      role,
      content,
      timestamp: Date.now()
    };
    conv.messages.push(msg);
    conv.updatedAt = Date.now();
    if (conv.title === "\u65B0\u5BF9\u8BDD" && role === "user" && content.trim()) {
      conv.title = content.substring(0, 30) + (content.length > 30 ? "..." : "");
    }
    this.save();
    return msg;
  }
  /** 更新指定消息内容（用于流式追加） */
  updateMessage(convId, msgId, content) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return false;
    const msg = conv.messages.find((m) => m.id === msgId);
    if (!msg)
      return false;
    msg.content = content;
    conv.updatedAt = Date.now();
    return true;
  }
  /** 设置对话的 Gateway sessionId */
  setSessionId(convId, sessionId) {
    const conv = this.conversations.get(convId);
    if (!conv)
      return false;
    conv.sessionId = sessionId;
    return true;
  }
  generateId() {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = Math.random() * 16 | 0;
      const v = c === "x" ? r : r & 3 | 8;
      return v.toString(16);
    });
  }
};

// src/views/chat.ts
var VIEW_TYPE_CHAT = "buddybridge-panel";
var BuddyBridgeChatView = class extends import_obsidian.ItemView {
  constructor(leaf, api) {
    super(leaf);
    this.isStreaming = false;
    this.api = api;
    this.manager = new ConversationManager();
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "BuddyBridge \u804A\u5929";
  }
  getIcon() {
    return "bot";
  }
  getManager() {
    return this.manager;
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("buddybridge-chat-container");
    this.tabBar = container.createDiv({ cls: "buddybridge-tab-bar" });
    const newBtn = this.tabBar.createEl("button", {
      text: "+",
      cls: "buddybridge-new-chat-btn",
      attr: { title: "\u65B0\u5EFA\u5BF9\u8BDD" }
    });
    newBtn.onclick = () => this.createNewChat();
    this.messageContainer = container.createDiv({ cls: "buddybridge-messages" });
    const inputArea = container.createDiv({ cls: "buddybridge-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      cls: "buddybridge-input",
      attr: { placeholder: "\u8F93\u5165\u6D88\u606F... (Shift+Enter \u6362\u884C\uFF0CEnter \u53D1\u9001)", rows: "2" }
    });
    this.inputEl.onkeydown = (e) => this.handleKeydown(e);
    const sendBtn = inputArea.createEl("button", {
      text: "\u53D1\u9001",
      cls: "buddybridge-send-btn"
    });
    sendBtn.onclick = () => this.sendMessage();
  }
  loadConversations(conversations) {
    this.manager.load(conversations);
    this.renderTabs();
    this.renderMessages();
  }
  createNewChat() {
    this.manager.createConversation();
    this.renderTabs();
    this.renderMessages();
  }
  switchToChat(id) {
    this.manager.switchTo(id);
    this.renderTabs();
    this.renderMessages();
  }
  deleteChat(id, e) {
    e.stopPropagation();
    this.manager.deleteConversation(id);
    this.renderTabs();
    this.renderMessages();
  }
  /** 渲染标签栏 */
  renderTabs() {
    var _a;
    const newBtn = this.tabBar.querySelector(".buddybridge-new-chat-btn");
    const oldTabs = this.tabBar.querySelectorAll(".buddybridge-tab");
    oldTabs.forEach((t) => t.remove());
    const conversations = this.manager.getAll();
    const activeId = (_a = this.manager.getActive()) == null ? void 0 : _a.id;
    for (const conv of conversations) {
      const tab = this.tabBar.createDiv({ cls: "buddybridge-tab" });
      if (conv.id === activeId) {
        tab.addClass("buddybridge-tab-active");
      }
      tab.createSpan({ text: conv.title, cls: "buddybridge-tab-title" });
      const closeBtn = tab.createSpan({ text: "\xD7", cls: "buddybridge-tab-close" });
      closeBtn.onclick = (e) => this.deleteChat(conv.id, e);
      tab.onclick = () => this.switchToChat(conv.id);
      if (newBtn) {
        tab.after(newBtn);
      }
    }
  }
  renderMessages() {
    this.messageContainer.empty();
    const conv = this.manager.getActive();
    if (!conv) {
      this.messageContainer.createDiv({
        text: "\u70B9\u51FB + \u65B0\u5EFA\u5BF9\u8BDD",
        cls: "buddybridge-empty-chat"
      });
      return;
    }
    for (const msg of conv.messages) {
      this.renderMessage(msg);
    }
    this.scrollToBottom();
  }
  renderMessage(msg) {
    const row = this.messageContainer.createDiv({
      cls: `buddybridge-message-row buddybridge-message-${msg.role}`
    });
    const bubble = row.createDiv({ cls: "buddybridge-bubble" });
    bubble.createSpan({ text: msg.content });
    return row;
  }
  async handleKeydown(e) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      await this.sendMessage();
    }
  }
  async sendMessage() {
    if (this.isStreaming)
      return;
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    let conv = this.manager.getActive();
    if (!conv) {
      conv = this.manager.createConversation();
      this.renderTabs();
    }
    const convId = conv.id;
    this.manager.addMessage(convId, "user", text);
    this.inputEl.value = "";
    this.renderMessages();
    const aiMsg = this.manager.addMessage(convId, "assistant", "");
    if (!aiMsg)
      return;
    this.renderMessages();
    const aiBubble = this.messageContainer.querySelector(
      `.buddybridge-message-assistant:last-child .buddybridge-bubble span`
    );
    this.isStreaming = true;
    try {
      let fullContent = "";
      for await (const chunk of this.api.sendMessage(conv.sessionId, text)) {
        fullContent += chunk;
        this.manager.updateMessage(convId, aiMsg.id, fullContent);
        if (aiBubble) {
          aiBubble.textContent = fullContent;
        }
      }
      this.manager.updateMessage(convId, aiMsg.id, fullContent);
      if (!conv.sessionId && fullContent) {
      }
    } catch (error) {
      this.manager.updateMessage(convId, aiMsg.id, `\u9519\u8BEF: ${error.message}`);
      new import_obsidian.Notice(`\u8BF7\u6C42\u5931\u8D25: ${error.message}`);
    } finally {
      this.isStreaming = false;
      this.renderMessages();
      this.renderTabs();
    }
  }
  scrollToBottom() {
    this.messageContainer.scrollTop = this.messageContainer.scrollHeight;
  }
};

// src/types.ts
var CURRENT_SETTINGS_VERSION = 1;
var DEFAULT_SETTINGS = {
  gatewayUrl: "http://127.0.0.1:55808",
  maxConversations: 20,
  version: CURRENT_SETTINGS_VERSION
};
function migrateSettings(stored) {
  if (!stored || typeof stored !== "object") {
    return { ...DEFAULT_SETTINGS };
  }
  const version = typeof stored.version === "number" ? stored.version : 0;
  const settings = {
    gatewayUrl: typeof stored.gatewayUrl === "string" ? stored.gatewayUrl : DEFAULT_SETTINGS.gatewayUrl,
    maxConversations: typeof stored.maxConversations === "number" && stored.maxConversations > 0 ? stored.maxConversations : DEFAULT_SETTINGS.maxConversations,
    version: CURRENT_SETTINGS_VERSION
  };
  return settings;
}

// src/settings/tab.ts
var import_obsidian2 = require("obsidian");
var BuddyBridgeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "BuddyBridge \u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("Gateway URL").setDesc("\u672C\u5730 WorkBuddy/CodeBuddy Gateway \u5730\u5740").addText((text) => text.setPlaceholder("http://127.0.0.1:55808").setValue(this.plugin.settings.gatewayUrl).onChange(async (value) => {
      this.plugin.settings.gatewayUrl = value;
      this.plugin.api.setGatewayUrl(value);
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u6700\u5927\u5BF9\u8BDD\u6570").setDesc("\u6700\u591A\u4FDD\u7559\u591A\u5C11\u4E2A\u5BF9\u8BDD\uFF08\u65E7\u5BF9\u8BDD\u5C06\u88AB\u81EA\u52A8\u5220\u9664\uFF09").addText((text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.maxConversations)).onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.maxConversations = num;
        await this.plugin.saveSettings();
      }
    }));
  }
};

// src/main.ts
var BuddyBridgePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.chatView = null;
  }
  async onload() {
    await this.loadSettings();
    this.api = new BuddyBridgeAPI(this.settings.gatewayUrl);
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => {
        this.chatView = new BuddyBridgeChatView(leaf, this.api);
        this.chatView.getManager().setPersistCallback(async (conversations) => {
          const data = await this.loadData() || {};
          data.conversations = conversations;
          await this.saveData(data);
        });
        this.loadPersistedConversations();
        return this.chatView;
      }
    );
    this.addRibbonIcon("bot", "BuddyBridge \u804A\u5929", async () => {
      await this.activateView();
    });
    this.addCommand({
      id: "buddybridge-open-chat",
      name: "\u6253\u5F00\u804A\u5929\u9762\u677F",
      callback: async () => {
        await this.activateView();
      }
    });
    this.addSettingTab(new BuddyBridgeSettingTab(this.app, this));
  }
  onunload() {
    this.api.cancel();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_CHAT)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_CHAT });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadPersistedConversations() {
    const data = await this.loadData();
    if (this.chatView) {
      this.chatView.loadConversations((data == null ? void 0 : data.conversations) || []);
    }
  }
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = migrateSettings(stored);
  }
  async saveSettings() {
    const existingData = await this.loadData() || {};
    const merged = { ...existingData, ...this.settings };
    await this.saveData(merged);
    this.api.setGatewayUrl(this.settings.gatewayUrl);
  }
};
